// generateReadme function populating the README.md
function generateMarkdown(answers) {
    return `# ${answers.projectTitle}
    ![Github licence](http://img.shields.io/badge/license-${answers.license}-blue.svg)

    ## Description
    ${answers.description}

    ## Table of Contents
    - [Description](#description)
    - [Installation](#installation)
    - [Usage](#usage)
    - [License](#license)
    - [Contributing](#contributing)
    - [Tests](#tests)
    - [Questions](#questions)
    ## Installation
    ${answers.installation}

    ## Usage
    ${answers.usage}

    ## License
    ![Github licence](http://img.shields.io/badge/license-${answers.license}-blue.svg)<br />
    This application is covered by the ${answers.license} license. 

    ## Contributing
    ${answers.contributing}

    ## Tests
    ${answers.tests}

    ## Questions
    Find me on GitHub: [${answers.username}](https://github.com/${answers.username})<br />
    Email me with any questions: ${answers.email}<br />
    This README file was generated by [README-generator](https://github.com/jpd61/README-generator) 
`;
}

module.exports = generateMarkdown;