// generateReadme function populating the README.md
const generateMarkdown = data => {
return `
# ${data.projectTitle}
![Github licence](http://img.shields.io/badge/license-${data.license}-blue.svg)

## Description
${data.description}

## Table of Contents
- [Description](#description)
- [Installation](#installation)
- [Usage](#usage)
- [License](#license)
- [Contributing](#contributing)
- [Tests](#tests)
- [Questions](#questions)

## Installation
${data.installation}

## Usage
${data.usage}

## License
![Github licence](http://img.shields.io/badge/license-${data.license}-blue.svg)<br />
This application is covered by the ${data.license} license. 

## Contributing
${data.contributing}

## Tests
${data.tests}

## Questions
Find me on GitHub: [${data.username}](https://github.com/${data.username})<br />
Email me with any questions: ${data.email}<br />
This README file was generated by [README-generator](https://github.com/jpd61/README-generator) 
`;
}

module.exports = generateMarkdown;