// create the video section
const generateVideo = videoText => {
    if (!videoText) {
        return '';
    }

    return `
And here is link to the video:[Screencastify](${videoText})  
`;
};

// generateReadme function populating the README.md
const generateMarkdown = data => {
    const video = generateVideo(data.video);
return `
# ${data.projectTitle}

![Github licence](http://img.shields.io/badge/license-${data.license}-blue.svg)

## Description

${data.description}

![Img for the application](${data.img})

## Table of Contents

- [Description](#description)
- [User Story](#user-story)
- [Acceptance Criteria](#acceptance-criteria)
- [Installation](#installation)
- [Usage](#usage)
- [License](#license)
- [Contributing](#contributing)
- [Tests](#tests)
- [Questions](#questions)

## User Story

${data.uesrStory}

## Acceptance Criteria

${data.acceptanceCriteria}

## Installation

${data.installation}

## Usage

${data.usage}

${video}

## License

![Github licence](http://img.shields.io/badge/license-${data.license}-blue.svg)<br />
This application is covered by the ${data.license} license. 

## Contributing

${data.contributing}

## Tests

${data.tests}

## Questions

Find me on GitHub: [${data.username}](https://github.com/${data.username})<br />
Email me with any questions: ${data.email}<br />
This README file was generated by [README-generator](https://github.com/zwind66/README-generator) 
`;
}

module.exports = generateMarkdown;